version: "3.9"

services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=taskdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root123456
      - MYSQL_ROOT_PASSWORD=root123456
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
     - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db